# Generated by Django 6.1.1 on 2026-09-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cigaretteentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cigaretteentry',
            name='time',
        ),
        migrations.AddField(
            model_name='cigaretteentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-09-24 17:42:31'),
            preserve_default=False,
        ),
    ]
